//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTask.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать всё.
        /// </summary>
        public static string MainWindow_PiecewiseLinearFunctionTable_ContextMenu_CopyAll {
            get {
                return ResourceManager.GetString("MainWindow.PiecewiseLinearFunctionTable.ContextMenu.CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать выделенное.
        /// </summary>
        public static string MainWindow_PiecewiseLinearFunctionTable_ContextMenu_CopySelected {
            get {
                return ResourceManager.GetString("MainWindow.PiecewiseLinearFunctionTable.ContextMenu.CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выделенное.
        /// </summary>
        public static string MainWindow_PiecewiseLinearFunctionTable_ContextMenu_DeleteSelected {
            get {
                return ResourceManager.GetString("MainWindow.PiecewiseLinearFunctionTable.ContextMenu.DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string MainWindow_PiecewiseLinearFunctionTable_ContextMenu_Paste {
            get {
                return ResourceManager.GetString("MainWindow.PiecewiseLinearFunctionTable.ContextMenu.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абсолютная отметка [мм].
        /// </summary>
        public static string MainWindow_PiecewiseLinearFunctionTable_X {
            get {
                return ResourceManager.GetString("MainWindow.PiecewiseLinearFunctionTable.X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура [С].
        /// </summary>
        public static string MainWindow_PiecewiseLinearFunctionTable_Y {
            get {
                return ResourceManager.GetString("MainWindow.PiecewiseLinearFunctionTable.Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовое задание POSPEX.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
    }
}
